### ISSUE TITLE
[BUG] The (Paste reference) button appears only after the page is reloaded

### ISSUE THREAD

**Issue by georggood** [Kephson/paste_reference#79]
## Summary / Description

The (Paste reference) button appears only after the page is reloaded. It is the page Reload button in the admin panel that helps. The page reload button in the browser does not solve the problem.

## Version

TYPO3 13.4.9 / paste_reference 4.0.2

## Steps to reproduce

1. Copy the content element
2. Click the button: Paste into this column
3. You will not see the Paste reference button
4. Click the - Reload button at the top of the page
5. Click the button: Paste into this column
6. You will see the Paste reference buttons

Video:

https://github.com/user-attachments/assets/18b471ad-ca96-4641-9127-5cdd15f39ddd

**Comment by DavidBruchmann** [comment]
Thanks for reporting the issue.
I can reproduce and confirm the behavior.
I leave it open, if it's useful to copy elements on the same page, but it's a bug and should be fixed.

**Comment by DavidBruchmann** [comment]
@georggood please check the my latest PR, after refactoring it seems the issue is gone.

**Comment by georggood** [comment]
@DavidBruchmann Hi, I used TYPO3 13.4.14 / paste_reference 4.0.2. Are there any changes for this version of the code? Is it worth checking them?
I don't use v3 / TYPO3 v12 and can't help with checking.

**Comment by DavidBruchmann** [comment]
@georggood thanks for the quick reply.
I feared that you're not interested in v12, but if you'd like to test I'd be glad about it.
I'm working on v4 for TYPO3 v13 and will push it soon.

**Comment by georggood** [comment]
Hello @DavidBruchmann ,

I tested with TYPO3v13.4.19.
Unfortunately, the issue persists. A page refresh is still required.
Will you reopen this ticket?

**Comment by DavidBruchmann** [comment]
sure, regrettable I wasn't able to finish a further release yet. but it's in work.

**Comment by DavidBruchmann** [comment]
Please use the latest branch https://github.com/Kephson/paste_reference/tree/refs/heads/v4-dev to check the behavior.
Any feedback would be helpful to give green light for the next release -- even if I still had to fix something.

Donations on https://ko-fi.com/davidbruchmann are very welcome, 10 or 20 bucks make already a difference for me!

Btw. further code improvement and also support for TYPO3 v14 are planned within short time.

**Comment by georggood** [comment]
Hello @DavidBruchmann ,

> Please use the latest branch https://github.com/Kephson/paste_reference/tree/refs/heads/v4-dev to check the behavior. Any feedback would be helpful to give green light for the next release -- even if I still had to fix something.

I tested it with TYPO3v13.4.23.
The problem persists.
The bug behaves the same as before.

Best regards

**Comment by DavidBruchmann** [comment]
@georggood thanks for testing!
For me it's working well though, as you can see on the gif:

![Image](https://github.com/user-attachments/assets/218a3390-4e9f-441e-ace5-b8e63f5bc4d4)

Please let me know which operating system and browser you're using and if you can see any messages in the browser console that could help to narrow the issue.
If you also could provide the version of EXT:container and if you use EXT:container_elements, the version of that too.
Thanks for your help, I'd be glad if we could tackle that issue!

**Comment by georggood** [comment]
Hi @DavidBruchmann ,

Thanks.

> Please let me know which operating system and browser you're using and if you can see any messages in the browser console that could help to narrow the issue.

Google Chrome ver: 144.0.7559.59
Ubuntu 22.04
TYPO3 v13.4.23
container	3.2.0
content_defender 3.5.3

Best regards

**Comment by DavidBruchmann** [comment]
thanks @georggood , even only once, I could reproduce the issue. therefore it's very hard to track it down.
Nevertheless, I think the most recent change is assuring that the code is only executed when the most recent clipboard data are retrieved.
So I hope it's working for you now and would be glad if you could test another time!

**Comment by DavidBruchmann** [comment]
@georggood maybe I was unclear. I populated the branch v4-dev, so you just could execute "git pull" to get the most recent state.
I'd appreciate your feedback about the changes and hope your issue is solved.
Of course, I'd try harder if it still exists.

**Comment by georggood** [comment]
@DavidBruchmann I downloaded the latest version of the extension and installed TYPO3v13.4.24.
But I still get the same issue and the same bag.

**Comment by DavidBruchmann** [comment]
Hi @georggood ,

in a common setup the branch works quite well, so I'd need your setup with content defender and some data.
You can send me everything confidentially by mail david.bruchmann@gmail.com or find me on the TYPO3 slack server.
As a recent issue about problems with powermail was reported(#94 ), consider to provide further info perhaps.
